version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: pmdb
      POSTGRES_USER: pmuser
      POSTGRES_PASSWORD: pmpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
